import { listToolDefinitions } from './toolRegistry.js'

export function getHelpMarkdown(): string {
  const tools = listToolDefinitions().map((tool) => `- \`${tool.name}\` — ${tool.description}`)

  return [
    '# ubersuggest-mcp-cf help',
    '',
    'Cloudflare Worker entrypoint for the Ubersuggest MCP hybrid deployment.',
    'Normal MCP traffic runs on Cloudflare. Browser bootstrap/reconnect is delegated to the separate AWS bootstrap backend.',
    '',
    '## Public routes',
    '',
    '- `GET /health` — basic health check',
    '- `GET /help` — this help page',
    '- `GET /guide` — lightweight HTML usage guide',
    '- `GET /.well-known/oauth-protected-resource` — MCP protected resource metadata',
    '- `GET /.well-known/oauth-authorization-server` — OAuth authorization server metadata',
    '- `GET /.well-known/openid-configuration` — OpenID-compatible metadata alias',
    '- `GET|POST /a` and `/authorize` — browser login + authorization code flow',
    '- `POST /t` and `/token` — exchange authorization code for bearer token',
    '- `POST /r` and `/register` — dynamic client registration',
    '- `GET|POST /invite` — redeem invite and set runtime password',
    '- `GET|POST /connect` — browser cookie paste/upload reconnect helper',
    '- `GET|POST /auth` — paste long OAuth URL and continue with shorter URL',
    '- `GET|POST /reconnect` — connect-link minting and reconnect start',
    '- `GET /reconnect/{jobId}` — check reconnect job status',
    '- `POST /logout` — clear the authenticated user session',
    '- `ANY /invoke-tool` — direct tool invocation over HTTP',
    '- `ANY /mcp` — MCP HTTP endpoint',
    '',
    '## Authentication',
    '',
    'Authenticated routes require a bearer token present in `Authorization: Bearer <token>`.',
    'For local MVP testing you can still use tokens from `UBERSUGGEST_AUTH_TOKENS_JSON`.',
    'OAuth authorization-code + PKCE routes are also available and issue bearer tokens for MCP access.',
    '',
    '## Available tools',
    '',
    ...tools,
    '',
    '## Reconnect flow',
    '',
    '1. Call `ubersuggest_auth_reconnect` over MCP or `POST /reconnect` over HTTP.',
    '2. Cloudflare records a reconnect job and calls the AWS bootstrap backend.',
    '3. AWS captures fresh runtime auth from a real browser session.',
    '4. Cloudflare stores encrypted auth material in D1 and marks the session ready.',
  ].join('\n')
}
